[http]

  [http.routers]
    [http.routers.routerTest]
      service = "k3s"
      rule = "Host(`192.168.201.30`)"

  [http.services]
    [http.services.k3s]
      [http.services.k3s.loadBalancer]
        [[http.services.k3s.loadBalancer.servers]]
          url = "https://192.168.201.11:6443"
        [[http.services.k3s.loadBalancer.servers]]
          url = "https://192.168.201.12:6443"
        [[http.services.k3s.loadBalancer.servers]]
          url = "https://192.168.201.13:6443"
