[entryPoints]
  [entryPoints.websecure]
    address = ":6443"
    [entryPoints.websecure.http.tls]
      [[entryPoints.websecure.http.tls.domains]]
        main = "192.168.201.30"

[providers.file]
  directory = "/tmp/traefikconf/"
  
[serversTransport]
  insecureSkipVerify = true
